# Site
name: "slandarer"
description: "My Simple Personal Blog"
meta_description: "Simple Personal Blog by slandarer"
logo: 'assets/images/miral-achmed-1.png'
favicon: 'favicon.ico'
url: 'https://slandarer.github.io'
baseurl: ''
google_analytics: 'UA-86909679-1'
disqus: 'slandarer.github.io'
mailchimp-list: ''
permalink: /:year/:month/:day/:title
future: true

# Authors
authors:
  miral:
    name: Miral Achmed
    display_name: Miral Achmed
    gravatar: 3654d753e5a623523e5190e7b3ec59e5
    email: miral.achmed@gmail.com
    web: https://slandarer.github.io 
    twitter: "none"
    instagram: "none"
    description: "这个人很懒，什么都不想写！！"

# Plugins
plugins: 
  - jekyll-paginate
  - jekyll-archives
  - jekyll-compose
  - jemoji
    
# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
    
# Pagination 
paginate: 6
paginate_path: /page:num/
    
# Other
markdown: kramdown
highlighter: rouge
